 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
<!--     <parent> -->
<!--         <groupId>nl.uu.fi.dwo</groupId> -->
<!--         <artifactId>DWO.master.pom</artifactId> -->
<!--         <version>1.1</version> -->
<!--         <relativePath>../../DWO-master-pom/pom.xml</relativePath> -->
<!--     </parent> -->
    <groupId>nl.uu.fi.dwo.lms</groupId>
    <artifactId>DwoGwtClientHtmlUi</artifactId>
    <version>2.3.2</version>
    <build>
        <plugins>
        	<plugin>
        	    <groupId>nl.geodienstencentrum.maven</groupId>
        		<artifactId>sass-maven-plugin</artifactId>
        		<version>3.6.1</version>
        		<configuration>
        			<resources>
        				<resource>
         					<source>
             					<directory>src/main/html/css/scss</directory>
             					<includes>
                 					<include>*.scss</include>
             					</includes>
	         				</source>
	         				<destination>${project.build.directory}/${project.build.finalName}/css</destination>
       					</resource>
     				</resources>
     				<relativeOutputDirectory>../..</relativeOutputDirectory>
     				<sassOptions>
     					<style>:compressed</style>
     				</sassOptions>
        		</configuration>
        		<executions>
        			<execution>
        				<goals>
        					<goal>update-stylesheets</goal>
        				</goals>
        			</execution>
        		
        		</executions> 
        	</plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.22.1</version>
                <configuration>
                    <images>
                        <image>
                            <alias>service</alias> 
                            <name>dwo/dwogwtclienthtmlui:${project.version}</name>                            
                            <build> 
                                <dockerFileDir>.</dockerFileDir>
                                <from>httpd:2.4</from> 
<!--                                <cmd> 
                                    <shell>COPY ./httpd.conf /usr/local/apache2/conf/</shell>
                                </cmd>-->
                            </build>
                            <run>
                                <!--docker run -v `pwd`/src:/usr/local/apache2/htdocs/local -p 127.0.0.1:8888:80 -dit - -name local-ebs-dev-proxy docker-local-ebs-dev-proxy-->
                                <ports>
                                    <port>0.0.0.0:8888:80</port>
                                </ports>
                                <volumes>
                                    <bind>
                                        <volume>${project.basedir}/src/main/html:/usr/local/apache2/htdocs/local</volume>
                                    </bind>
                                </volumes>
                            </run>
                        </image>
                    </images>
                </configuration>
            </plugin>
             <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <warSourceDirectory>src/main/html</warSourceDirectory>
                    <failOnMissingWebXml>false</failOnMissingWebXml>           
                </configuration>
            </plugin>
        </plugins>
    </build>
    <packaging>war</packaging>
    <!-- automagically use snapshot/release, not in parent pom -->
   <distributionManagement>
        <snapshotRepository>
            <id>snapshots</id>
            <name>libs-snapshot</name>
            <url>https://repos.dwo.nl/artifactory/libs-snapshot-local</url>    
        </snapshotRepository>
        <repository>
            <id>release</id>
            <name>libs-release</name>
            <url>https://repos.dwo.nl/artifactory/libs-release-local</url>    
        </repository>
    </distributionManagement>
    <scm>
    	<developerConnection>scm:git:git@git.science.uu.nl:dwoproject/DWO-LMS/DwoGwtClientHtmlUi.git</developerConnection>
    </scm>
    <profiles>
    	<profile>
    		<id>gitflow</id>
    		<build><plugins>
   			<plugin>
            	<groupId>external.atlassian.jgitflow</groupId>
            	<artifactId>jgitflow-maven-plugin</artifactId>
            	<version>1.0-m5.1</version>
            	<configuration>
                	<!-- see goals wiki page for configuration options -->
                	<flowInitContext>
             			<developBranchName>teuniz</developBranchName>       	
                	</flowInitContext>                	
            	</configuration>
        	</plugin>
    		</plugins></build>
    	</profile>
    </profiles>
</project>
